### PR TITLE
fix: Gitlab resolver

### LINKED ISSUE #7603: PNPM Git Resolver: Incorrect Branch Installation
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

8.15.1

### Which area(s) of pnpm are affected? (leave empty if unsure)

Dependencies resolver, CLI

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/datrhi/pnpm-git-resolve-bug

### Reproduction steps

1. **Clone the Repository:**
- git clone https://github.com/datrhi/pnpm-git-resolve-bug
2. **PNPM Install:**
- pnpm install

## PNPM Git Resolver Issue: Incorrect Branch Installation

When specifying a Git dependency in `package.json`, PNPM unexpectedly installs the `master` branch instead of the explicitly declared `empty` branch. This behavior contrasts with Yarn, which accurately installs the specified `empty` branch for the `react-native-camera-kit` dependency. This inconsistency in PNPM's interpretation of Git URLs compared to Yarn can lead to potential confusion and errors in dependency management.

### Understanding the Issue

The `package.json` declaration for installing a Git dependency is as follows:

```json
"dependencies": {
  "react-native-camera-kit": "git+https://gitlab.com/dung.huynh1/react-native-camera-kit.git#empty"
}
```

This line instructs the package manager to clone the react-native-camera-kit repository from the specified GitLab URL, specifically targeting the empty branch. While Yarn follows this directive accurately, PNPM diverges by defaulting to the repository's main branch (commonly master), ignoring the branch specifier in the URL.

### Expected Behavior

Installing the Exact Version of a Dependency

### Which Node.js version are you using?

14.21.3

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by datrhi**
fix: https://github.com/pnpm/pnpm/issues/7603

### CODE REVIEW

File: git-host-info.js [hunk 1]
```diff
@@ -76,7 +76,7 @@ gitHosts.gitlab = Object.assign({}, defaults, {
   domain: 'gitlab.com',
   treepath: 'tree',
   httpstemplate: ({ auth, domain, user, project, committish }) => `git+https://${maybeJoin(auth, '@')}${domain}/${user}/${project}.git${maybeJoin('#', committish)}`,
-  tarballtemplate: ({ domain, user, project, committish }) => `https://${domain}/${user}/${project}/repository/archive.tar.gz?ref=${maybeEncode(committish) || 'master'}`,
+  tarballtemplate: ({ domain, user, project, committish }) => `https://${domain}/${user}/${project}/repository/archive.tar.gz?sha=${maybeEncode(committish) || 'master'}`,
```
Comment (zkochan) [inline git-host-info.js:79]: will this both work when the params is a commit hash or a branch name as "master"?

Comment (datrhi) [reply git-host-info.js:79]: > will this both work when the params is a commit hash or a branch name as "master"?

ofc, see gitlab document: https://docs.gitlab.com/ee/api/repositories.html#get-file-archive

Comment (zkochan) [reply git-host-info.js:79]: great, thanks for the link

**Review by zkochan — APPROVED** [review]
